### ISSUE TITLE
Lunch Map

### ISSUE THREAD

**Issue by linyows** [fukuokago/fukuoka.gocon.jp#14]
Tell me your recommendation diners, please!

Requirements

- Open in Saturday
- Nearly 大名
- Yammy~

Template

`- [Diner Name](https://tabelog.com/)`

**Comment by linyows** [comment]
とりあえず思いつくもの

- [ひらお]()
- [Stereo]()
- [赤のれん]()
- [ツナパハ]()
- [かまきりうどん]()
- [十一]()
- [八幡]()
- [弁天堂]()
- [Fish&Cat]()
- [ヒッコリー2]()
- [おむや]()
- [やぶ金]()
- [かりんこ]()
- [チー坊]()
- [かし和]()
- [マルワ食堂]()
- [あさ山]()
- [ラムガンディ]()
- [松島]()
- [うどん大学]()
- [ライオン食堂]()
- [いっかく食堂]()
- [素や]()
- [あんず]()

**Comment by seike460** [comment]
追加で思いつくもの

- [一風堂]()
- [ニクゼン]()
- [桝本]()
- [三昧]()
- [たかお]()
- [大名ちんちん]()
- [SHIP’S LOG]()
- [大砲ラーメン]()
- [兼虎]()
- [おいげん]()
- [秀ちゃんラーメン]()

**Comment by linyows** [comment]
兼虎いいですね！

**Comment by seike460** [comment]
とりあえず埋め込み
土日調べていきます

【直接参照】
https://www.google.com/maps/d/embed?mid=1QB35AAvbnwmqkuoVfpQqlxdAOUTNX0Bh&hl=ja
【HTML埋め込み】
<iframe src="https://www.google.com/maps/d/embed?mid=1QB35AAvbnwmqkuoVfpQqlxdAOUTNX0Bh&hl=ja" width="640" height="480"></iframe>

**Comment by seike460** [comment]
現状上がってるのは地図に貼り付けてます

- 土日を調べた（日曜日のみ定休日とかあるんすね）
- 食べログを貼った
- 大まかに分類して色分けした

**Comment by seike460** [comment]
# 初期表示

![初期表示](https://user-images.githubusercontent.com/8141624/57569109-2d10c400-742b-11e9-8e2a-472174f79170.png)

# この状態で開けたら便利…

![この状態で開きたい](https://user-images.githubusercontent.com/8141624/57569090-fe92e900-742a-11e9-99cb-2d41d081a687.png)

**Comment by seike460** [comment]
# 既存地図バージョン

パット見の表示確認の為、Location.vueに混ぜちゃってます※後で消します！
ちなみにチー坊です。

![既存地図バージョン](https://user-images.githubusercontent.com/8141624/57569179-33537000-742c-11e9-8bf1-72027f2342d3.png)

**Comment by linyows** [comment]
大体できてるので閉じ
